ResolveSpecDjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^manual/', include('manual.urls', namespace="manual")),
                       url(r'^plot/',
                           include('treeplot.urls', namespace="treeplot")),
]

manual/urls.py
from django.conf.urls import patterns, url
from manual import views

urlpatterns = patterns('',
                       # index
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       url(r'^list/$', views.List.as_view(), name='list'),
                       url(r'^(?P<slug>[\w\-]+)/$',
                           views.PostView.as_view(), name='posts'),
                       )

resolvespec/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
                       # index
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       )

treeplot/urls.py
from django.conf.urls import patterns, include, url
from treeplot import views

urlpatterns = patterns('', 
	#index
	url(r'^$', views.treetest, name='index'),
        url(r'^getTree', views.treetest, name='getTree'),
	)

manual/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Post(models.Model):
    title = models.CharField(max_length=60)
    slug = models.SlugField(unique=True, max_length=255)
    description = models.CharField(max_length=255)
    content = models.TextField()
    published = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('manual.views.post', args=[self.slug])

resolvespec/models.py
from django.db import models

# Create your models here.


class Node(models.Model):
    name = models.CharField(max_length=200)
    parent = models.ManyToManyField(
        "self", related_name="children", blank=True)
    oneormany = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name


class Content(models.Model):
    node = models.ForeignKey(Node)
    description = models.CharField(max_length=255)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    last_edited = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.node.name

treeplot/models.py
from django.db import models

# Create your models here.

manual/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.core.paginator import Paginator, InvalidPage, EmptyPage
# from django.core.urlresolvers import reverse
from django.views import generic

from manual.models import *


class IndexView(generic.ListView):
    template_name = 'manual/list2.html'
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        return Post.objects.filter(published=True)


class List(generic.ListView):
    template_name = 'manual/tree.html'
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        return Post.objects.filter(published=True)


def index(request):
    """Main listing."""
    posts = Post.objects.filter(published=True)
    paginator = Paginator(posts, 2)

    try:
        page = int(request.GET.get("page", '1'))
    except ValueError:
        page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render_to_response("manual/tree.html", dict(
        posts=posts, user=request.user))


class PostView(generic.DetailView):
    model = Post
    template_name = 'manual/post.html'


def post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'manual/post.html', {'post': post})

resolvespec/views.py
from django.shortcuts import render
from resolvespec.models import Node
from django.views.generic.list import ListView
# Create your views here.


class IndexView(ListView):
    template_name = 'resolvespec/index.html'
    context_object_name = 'nodes'

	# def get_queryset(self):

treeplot/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json

# Create your views here.


def treetest(request):
    myTree = {'children': [], 'title': 'Root',
              'isFolder': True, 'hideCheckbox': True}
    myTree['children'].append(
        {'title': 'Child 1', 'isFolder': 'false', 'children': []})
    myTree['children'].append(
        {'title': 'Child 2', 'isFolder': 'false', 'children': []})
    myTree['children'].append(
        {'title': 'Child 3', 'isFolder': 'false', 'children': []})

    # Convert result list to a JSON string
    res = json.dumps(myTree, encoding="Latin-1")

    # Support for the JSONP protocol.
    response_dict = {}
    if request.GET.has_key('callback'):
        response_dict = request.GET['callback'] + "(" + res + ")"

    return HttpResponse(response_dict, mimetype='application/json')

    response_dict = {}
    response_dict.update({'children': tree})
    return HttpResponse(response_dict, mimetype='application/javascript')

manual/templates/manual/bbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>{% block title %}Title{% endblock %}</title>
{% load staticfiles %}
{% include 'manual/scripts.html' %}
{% block scripts %} {% endblock %}
</head>
<body>
	<div id="container">
		<!-- Container -->
		<div id="menu">
			{% block nav-global %}
				<!-- MENU -->
				<h3>Title</h3>
				{% if user.is_staff %}
				<a href="{% url 'admin:index' %}">Admin</a>
				<a href="{% url 'admin:manual_post_add' %}">Add Post</a>
				{% endif %}
				<!-- End MENU -->
			{% endblock %}
		</div>
		<div id="content">
			<!-- Content -->
			<div id="sidebar"> {% block sidebar %} {% endblock%}</div>
			<div id="main">
				{% block main %}{% endblock %}
			</div>
			<!-- End Content -->
		</div>
		<!-- End Container -->
	</div>
</body></html>

manual/templates/manual/list.html
{% extends "manual/bbase.html" %}
{% load staticfiles %}
{% block main %}
<!-- Posts -->
{% for post in posts %}
	<div class="window">
		<div class="title">
			<a href="{% url 'manual:posts' post.slug%}">{{ post.title }}</a> <div class="button" data-buttoniter="{{ post.id }}">-</div>
		</div>
		<div class="time">{{ post.created }}</div>
		<div class="box" data-boxiter="{{ post.id }}">
		{% autoescape off %} <div class="body">{{ post.content|linebreaks }}</div>{% endautoescape %}
		</div>
	</div>
{% endfor %}
<!-- End Posts -->

<!-- Next/Prev page links -->
{% if is_paginated %}
<div class="pagination" style="margin-top: 20px; margin-left: -0px; ">
	<span class="step-links">
		{% if page_obj.has_previous %}
			<a href= "?page={{ page_obj.previous_page_number }}">newer entries &lt;&lt; </a>
		{% endif %}
		
		<span class="current">
			&nbsp;Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
		</span>
		
		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">&gt;&gt; older entries</a>
		{% endif %}
	</span>
</div>
{% endif %}
{% endblock %}

manual/templates/manual/list2.html
{% extends "manual/bbase.html" %}
{% load staticfiles %}
{% block main %}

<iframe src="list/" name="listframe" id="listframe" frameborder="0" marginwidth="0" marginheight="0" scrolling="auto" onload="" ></iframe>

{% endblock %}

{% block sidebar %} 
<div id="treeViewDiv">
</div>

<script>
$(function (){
	
	
	
	$("#treeViewDiv").jstree({ 'core' : {
		'data' : [
		{
		'text' : 'Facilities',
		'a_attr' : {'href' : "{% url 'manual:list' %}"},
		'state' : {
			'opened' : true
			},
		'children' : [
			{% for post in posts %}
			{
			'text' : "{{post.title}}",
			'a_attr' : {'href' : "{% url 'manual:posts' post.slug%}"},
			'children' : [],
			'state' : {
			'opened' : false,
			'selected' : false
			}
			},
			{% endfor %}
		]
		}
		]
		}
	})
	.bind('select_node.jstree', function(e, data) {
		var href = data.node.a_attr.href;
		if(href !== undefined){
			window.top.frames['listframe'].location = href;
		}
		});
})
</script>
{% endblock %}

manual/templates/manual/post.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<html>
<head>
{% load staticfiles %}
{% include 'manual/scripts.html' %}
</head>

<body class="framed">
	<article>
		<header>
			<h1>{{ post.title }}</h1>
			<p> Posted on <time datetime="{{ post.created|date:'c'}}">
			{{ post.created|date }}
			</time>
			</p>
		</header>
		<p class="description">
			<i>{{ post.description }}</i>
		</p>
		{{post.content|safe}}
	</article>
</body>
</html>

manual/templates/manual/scripts.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'manual/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'manual/normalize.css' %}">
<link rel="stylesheet" href="{% static 'manual/scripts/jstree/dist/themes/default/style.min.css' %}"
 />
<script type='text/javascript' src="{% static 'manual/scripts/jquery-2.1.1.min.js' %}"></script>
<script type='text/javascript' src="{% static 'manual/scripts/jstree/dist/jstree.min.js' %}"></script>


<script type='text/javascript'>
$(window).load(function(){
	$(".button").click(function(){
		var t = "[data-boxiter=" + $(this).attr('data-buttoniter') + "]";
		if($(this).html() == "-"){
			$(this).html("+");
		}
		else{
			$(this).html("-");
		}
		$(t).slideToggle();
	});
});


</script>

manual/templates/manual/sidebar.html
{% block sidebar %} 
<div id="treeViewDiv">
</div>

<script>
$(function (){
	$("#treeViewDiv").jstree({ 'core' : {
		'data' : [
		   'Simple root node',
		   {
			 'text' : 'Root node 2',
				'a_attr' : { "href" : "t2/"
				},
			 'state' : {
			   'opened' : true,
			   'selected' : true
			 },
			 'children' : [
			   { 'text' : 'Child 1',
				'a_attr' : { "href" : "t2/"
				}
			   },{
			    'text' : 'Child 2',
				'a_attr' : { "href" : "t2/"
				}
				}
			 ]
		  }
		]
		}, 'plugins' : ['dnd'] 
	})
	.bind('select_node.jstree', function(e, data) {
		var href = data.node.a_attr.href;
		if(href !== undefined){
			window.top.frames['listframe'].location = href;
		}
		});
})
/*$(function () {
	$('#jstree_demo_div').jstree();
	$('#jstree_demo_div').on("changed.jstree", function (e, data) {
		console.log(data.selected);
		});
	$('button').on('click', function() {
		$('#jstree').jstree(true).select_node('child_node_1');
		$('#jstree').jstree('select_node', 'child_node_1');
		$.jstree.reference('#jstree').select_node('child_node_1');
		});
})*/
</script>
{% endblock %}

manual/templates/manual/tree.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'manual/pyg.css' %}"
 />
{% include 'manual/scripts.html' %}
</head>

<body class="framed">
{% for post in posts %}
	<div class="window">
		<div class="title">
			<a href="{% url 'manual:posts' post.slug%}">{{ post.title }}</a> <div class="button" data-buttoniter="{{ post.id }}">-</div>
		</div>
		<div class="time">{{ post.created }}</div>
		<div class="box" data-boxiter="{{ post.id }}">
		{% load pygmentify %}{% autoescape off %} 
		<!--<pre class="body">{{ post.content|linebreaks }}</div>-->
		{{ post.content|pygmentify|linebreaks }}
		{% endautoescape %}
		</div>
	</div>
{% endfor %}
<!-- End Posts -->

<!-- Next/Prev page links -->
{% if is_paginated %}
<div class="pagination" style="margin-top: 20px; margin-left: -0px; ">
	<span class="step-links">
		{% if page_obj.has_previous %}
			<a href= "?page={{ page_obj.previous_page_number }}">newer entries &lt;&lt; </a>
		{% endif %}
		
		<span class="current">
			&nbsp;Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
		</span>
		
		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">&gt;&gt; older entries</a>
		{% endif %}
	</span>
</div>
{% endif %}
</body></html>

treeplot/templates/treeplot/base.html
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><title>{% block title %}Tree Plotting{% endblock %}</title><script src='/media/jquery-1.10.2.min.js' type="text/javascript"></script><script src='/media/jqueryui/ui/jquery-ui.js' type="text/javascript"></script><script src='/media/jquery/jquery.cookie.js' type="text/javascript"></script>{% block head %} {% endblock %}</head><body><div id="container">	<!-- Container -->	<div id="content">		<!-- Content -->		{% block content %}{% endblock %}	</div></div></body>

treeplot/templates/treeplot/jquery.html
{% extends "treeplot/base.html" %}

{% block head %} 
<!-- empty -->
{% endblock %}

{% block content %}
	<script>
		$(function() {
			
		}); // end function()
	</script>
	<div id="tree"></div>
{% endblock %}